apiVersion: v2
type: application
name: switchboard
version: 0.0.0
appVersion: 0.0.0
home: https://github.com/borchero/switchboard
sources:
  - https://github.com/borchero/switchboard
keywords:
  - dns
  - tls
  - external-dns
  - cert-manager
  - traefik
  - dnsendpoint

dependencies:
  - name: external-dns
    version: 8.7.11
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: dependencies.external-dns.install
  - name: cert-manager
    version: 1.17.1
    repository: https://charts.jetstack.io
    condition: dependencies.cert-manager.install
