version: 2
updates:
  # Update GitHub actions
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: ci
    labels:
      - dependencies
  # Update Go dependencies
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: build(go)
    labels:
      - dependencies
  # Update Docker base images
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
    groups:
      docker-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: build(docker)
    labels:
      - dependencies
