run:
  timeout: 10m
linters:
  enable:
    - goimports
    - revive
    - stylecheck
issues:
  include:
    - EXC0002
    - EXC0014
linters-settings:
  revive:
    rules:
      - name: unused-receiver
        severity: warning
