name: Check Code
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - chart/**
  push:
    branches:
      - main
    paths-ignore:
      - chart/**

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Code
        run:
          golangci-lint run --exclude-use-default=false -E goimports -E revive --timeout 10m ./...

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: Setup Kubernetes Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: switchboard-tests
      - name: Deploy CRDs
        run: make setup-cluster KIND_CLUSTER_NAME=switchboard-tests
      - name: Run Unit Tests
        run: go test ./...
