name: Build Container Image
on:
  release:
    types:
      - published
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Gather File Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: none
          filters: |
            chart:
              - chart/**
      - name: Assemble Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,enable=${{ github.ref_name == 'main' }},event=branch
            type=sha,enable=${{ github.ref_type != 'tag' && steps.changes.outputs.chart == 'true' }},prefix=gh-actions-,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        if: |
          github.ref_type == 'tag'
          || (github.ref_type == 'pull_request' && steps.changes.outputs.chart == 'true')
          || (github.ref_type == 'branch' && github.ref_name == 'main')
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push:
            ${{ github.ref_type == 'tag' || (github.ref_type == 'pull_request' &&
            steps.changes.outputs.chart == 'true') || (github.ref_type == 'branch' &&
            github.ref_name == 'main') }}
          tags: ${{ steps.meta.outputs.tags }}
