name: Publish Helm Chart
on:
  release:
    types:
      - published

jobs:
  publish:
    name: Package and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
      - name: Login to GitHub OCI Registry
        run: |
          echo ${{ github.token }} | \
            helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Download Dependencies
        run: helm dependency build
        working-directory: ./chart
      - name: Package Chart
        run: |
          VERSION=${{ github.ref_name }}
          helm package . \
            --app-version ${VERSION#v} \
            --version ${VERSION#v}
        working-directory: ./chart
      - name: Push Chart
        run: |
          VERSION=${{ github.ref_name }}
          helm push switchboard-${VERSION#v}.tgz oci://ghcr.io/${{ github.actor }}/charts
        working-directory: ./chart
