name: Lint Helm Chart
on:
  pull_request:
    branches:
      - main
    paths:
      - chart/**
  push:
    branches:
      - main
    paths:
      - chart/**

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-20.04
    container: alpine/helm:3.8.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Chart
        run: helm lint
        working-directory: ./chart
