name: Cleanup
on:
  schedule:
    - cron: 30 3 * * MON

jobs:
  images:
    name: Cleanup Untagged Images
    runs-on: ubuntu-20.04
    steps:
      - name: Cleanup Untagged Images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.repository.name }}
          cut-off: 1 month ago UTC
          account-type: personal
          token: ${{ github.token }}
          untagged-only: true
